# Generated by Django 4.2.7 on 2024-12-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=50)),
                ('company_logo', models.CharField(max_length=250)),
                ('background_img', models.CharField(default='', max_length=250)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Speakers',
        ),
    ]
