# Generated by Django 4.2.7 on 2024-12-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_speaker_delete_speakers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='background_img',
            field=models.CharField(default='https://tse3.mm.bing.net/th?id=OIP.0gUPjiEc7C5OcGurQO4EmgHaMW&pid=ImgDet&w=194&h=323&c=7', max_length=250),
        ),
    ]
