# Generated by Django 4.2.7 on 2024-12-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_speaker_background_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('date', models.CharField(max_length=50)),
                ('timing_1', models.CharField(max_length=100)),
                ('timing_2', models.CharField(max_length=100)),
                ('timing_3', models.CharField(max_length=100)),
                ('timing_4', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
