# Generated by Django 4.2.7 on 2024-12-27 15:06

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name'),
        ),
    ]
