# Generated by Django 4.2.7 on 2024-12-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_speaker_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='background_img',
            field=models.CharField(default='https://th.bing.com/th/id/OIP.5iA9Ncrvp5gFpYAbxgEigQHaEK?w=248&h=181&c=7&r=0&o=5&dpr=1.3&pid=1.7', max_length=250),
        ),
    ]
