# Generated by Django 4.2.7 on 2024-12-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_speaker_background_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='background_img',
            field=models.CharField(default='static/images/WhatsApp Image 2024-12-30 at 02.03.28_ff78184b.jpg', max_length=250),
        ),
    ]
