# Generated by Django 4.2.7 on 2024-12-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_speaker_background_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='background_img',
            field=models.ImageField(default='back_ground_images/WhatsApp Image 2024-12-30 at 02.03.28_ff78184b.jpg', upload_to='back_ground_images/'),
        ),
    ]
