# Generated by Django 4.2.7 on 2024-12-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_speaker_background_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='background_img',
            field=models.CharField(default='https://www.scylladb.com/wp-content/uploads/Planet-Jodorowski-web.png', max_length=250),
        ),
    ]
